version: '3.7'

services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ['npm', 'start']
    ports:
      - '3100:3000'
    volumes:
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
    stdin_open: true
    environment:
      VIRTUAL_HOST: tech.test.docker
